eclipse-sirius/sirius-desktop

- Jenkinsfile
For now we only use the `Jenkinsfile` to run a subset of our tests to validate PRs.
Once a PR has been merged on master, there is no point in re-running these tests again. It only occupies slots on the CI server and slows down feedback on other PRs in progress.
This does not mean we do not run the (full) test suite on `master`, but given the time it takes to run this is in a different job than.
> [releng] Do not run PR checks once merged to master

- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/ControlUncontrolWithOpenedRepresentationTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/LockedRepresentationContainerTest.java
- plugins/org.eclipse.sirius.ui/src/org/eclipse/sirius/ui/tools/api/control/SiriusControlHandler.java
- plugins/org.eclipse.sirius.ui/src/org/eclipse/sirius/ui/tools/api/control/SiriusUncontrolHandler.java
- plugins/org.eclipse.sirius.ui/src/org/eclipse/sirius/ui/tools/internal/actions/control/DesignerControlAction.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/89
> [#89] Avoid deadlocks with Control/Uncontrol handlers

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/internal/command/ViewDeleteCommand.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/CanonicalSynchronizerResult.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/GMFHelper.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/listeners/NotationVisibilityUpdater.java
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/purelyGraphicalElementsBehavior/representations.aird
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/NoteAttachmentTest.java
Fix the indirect deletion of note attachment, when
deleting note/text.
Fix the indirect hiding of hiding note attachment when hiding edges.
This commit also corrects when a note/text is deleted or edge is hide,
with the "remove/hide note when attached element is removed" preference
enabled, the note attached indirectly is now properly removed or hidden.
Preference now works the same way for text in corrected cases.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/82
> [82] Fix disconnected note attachment problem with edge and note/text

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/edit/commands/StraightenToCommand.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/edit/policies/SiriusBaseItemSemanticEditPolicy.java
Fix the NPE from
org.eclipse.sirius.tests.swtbot.EdgeReconnectionTests.testSimpleEdgeSourceReconnectionWithObliqueStyleRouting()
It's strange, but this NPE is here since the commit 1e150a9b [1] (2022-07-06) for bugzilla 476523. It is only visible in automatic test (not when the end-user does the same action).
[1] https://github.com/eclipse-sirius/sirius-desktop/commit/1e150a9b90341029a9147a281606ffbfbd5507c8
[2] https://bugs.eclipse.org/bugs/show_bug.cgi?id=476523
> [test] Fix testSimpleEdgeSourceReconnectionWithObliqueStyleRouting

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/DDiagramEditorImpl.java
Sometimes in CI, a IndexOutOfBoundsException is observed in org.eclipse.sirius.tests.swtbot.sequence.InteractionUseTests.testInteractionUseDeletionByInstanceRoleDeletionPossible. This commit avoids this potential problem.
The observed stack is:
```
. Stack trace: java.lang.IndexOutOfBoundsException: Index: 0
at java.base/java.util.Collections$EmptyList.get(Collections.java:4586)
at org.eclipse.sirius.diagram.ui.tools.internal.editor.DDiagramEditorImpl.selectionChanged(DDiagramEditorImpl.java:1206)
at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:266)
at org.eclipse.ui.internal.e4.compatibility.SelectionService.handleSelectionChanged(SelectionService.java:98)
at org.eclipse.ui.internal.e4.compatibility.SelectionService.lambda$0(SelectionServ …
```
> [test] Fix a potential IndexOutOfBoundsException

- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/EdgeLabelsMoveFromEdgeMoveTest.java
A case was missed in the previous commit 8f8e544f [1].
[1] https://github.com/eclipse-sirius/sirius-desktop/commit/8f8e544fa49f222689e6399d0d44010279604f66
> [test] Fix EdgeLabelsMoveFromEdgeMoveTest regression - Round 2

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/actions/TabbarPasteFormatMenuManager.java
The org.eclipse.sirius.tests.swtbot.tabbar.TabBarTest allowed to detect that the new field actionHistory, in TabbarPasteFormatMenuManager, is not correctly cleaned during the dispose of the menu manager.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/9
> [9] Fix a regression detected by TabBarTest

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/layout/PasteImageAction.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/actions/TabbarPasteFormatMenuManager.java
This fix replace a null affectation with clear list, this fix should be temporary because the null affectation in dispose should be correct. The real bug is in another place.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/9
> [9] Fix an NPE caused by setting a variable to null in dispose

- plugins/org.eclipse.sirius.tests.junit.support/src/org/eclipse/sirius/tests/support/api/TestsUtil.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/LabelFontModificationsTest.java
Since Eclipse 202309, the Undo/Redo label is no longer followed by a space. I have not succeed to understand why.
The values have not been changed in properties file in [1] and [2], but it seems that somewhere the value is changed.
[1] https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/messages.properties#L85C23-L85C23
[2] https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/messages.properties#L824
> [test] Fix undo/redo label menu problem caused by new target platform

- packaging/org.eclipse.sirius.parent/pom.xml
- packaging/org.eclipse.sirius.tests.parent/pom.xml
This reverts commits cc8dbac6af6961ce1d8f55f1e7b8203d3502f6d9 and 71ae1945233fa1d091a888e1ad051dc97e1c3883.
> [test] Revert "temporarily set Xmx to 3072m instead of 2048m" commits

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/edit/commands/ChildrenAdjustmentCommand.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/util/EditPartQuery.java
Since ed645ff4183ab5775fefb79867e1e434c42c8866,
EditPartQuery.getBorderNodeEditParts() returned an *immutable* list
instead of a plain ArrayList before. Some client code (notably
ChildrenAdjustmentCommand.addBorderChildrenAdjustmentCommands()) try
to mutate the result, which would result in
UnsupportedOperationException.
Revert to returning a mutable List.
> [fix] Fix a potential UnsupportedOperationException

- plugins/org.eclipse.sirius.tests.swtbot.support/src/org/eclipse/sirius/tests/swtbot/support/api/AbstractSiriusSwtBotGefTestCase.java
During an execution of a suite, if some fail during the failureTearDown method execution, all the data used by these tests leak until the end of the suite execution.
This can be problematic in case of long suite with several failures and lot of data. It increases the risk of OutOfMemory error.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/144
> [144][test] Fix a memory leak regarding tests failures

- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/AbstractHideRevealDiagramElementsLabelTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/ContextMenuInDiagramTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/DiagramMouseZoomTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/DiagramZoomTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/DragAndDropFromControlledResourceTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/DragAndDropFromTableAndTreeToDiagramTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/EdgeCreationTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/EdgeSelectionTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/EdgeWithMultipleLabelsTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/LockedAppearanceTabTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/NodeBorderLabelPositionStabilityTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/PopupMenuTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/PortsOnNodePositionStabilityTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/RefreshAfterUndoDragNDropTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/RoutingStyleTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/SelectAllAndDeselectionTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/SessionSaveableTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/SpecificClosedOrNotClosedEditorTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/ToolCreationPositionTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/VSMAndDiagramEditorSynchronisationTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/LockedTabBarTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/NotInvisibleTabBarTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/ResetToDefaultFiltersActionTests.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/TabBarTest.java
Three variables duplicated in some child classes are removed from said sublclasses:
* SWTBotSiriusDiagramEditor editor
* UIResource sessionAirdResource
* UILocalSession localSession
> [cleanup] Suppression of variables declared in tests abstract superclass

- releng/org.eclipse.sirius.targets/capella/sirius_2023-03.target
- releng/org.eclipse.sirius.targets/capella/sirius_2023-03.targetplatform
- releng/org.eclipse.sirius.targets/headless/sirius_2023-03.target
- releng/org.eclipse.sirius.targets/headless/sirius_2023-03.targetplatform
- releng/org.eclipse.sirius.targets/modules/acceleo-3.7.tpd
- releng/org.eclipse.sirius.targets/modules/aql-3.7.tpd
- releng/org.eclipse.sirius.targets/modules/gmf-runtime-1.16.tpd
- releng/org.eclipse.sirius.targets/sirius_2022-09.target
- releng/org.eclipse.sirius.targets/sirius_2022-09.targetplatform
- releng/org.eclipse.sirius.targets/sirius_2022-12.target
- releng/org.eclipse.sirius.targets/sirius_2022-12.targetplatform
- releng/org.eclipse.sirius.targets/sirius_2023-03.target
- releng/org.eclipse.sirius.targets/sirius_2023-03.targetplatform
- releng/org.eclipse.sirius.targets/sirius_2023-06.target
- releng/org.eclipse.sirius.targets/sirius_2023-06.targetplatform
- releng/org.eclipse.sirius.targets/sirius_2023-09.target
- releng/org.eclipse.sirius.targets/sirius_2023-09.targetplatform
- releng/org.eclipse.sirius.targets/sirius_2023-12.target
- releng/org.eclipse.sirius.targets/sirius_2023-12.targetplatform
Only GEF Classic 3.18.0 (used only in the 2023-12 target platform) is
still pointing to a non-final location as they are still in RC1 at the
moment.
> [releng] Point to the final release URLs for our dependencies

- Jenkinsfile
The option "timestamps" is available only if Timestamper plugin [1] is installed on Jenkins.
This commit allows to verify that it is installed or not.
[1] https://plugins.jenkins.io/timestamper/
> [releng] Try to enable Timestamp on console

- plugins/org.eclipse.sirius.diagram.sequence/src/org/eclipse/sirius/diagram/sequence/business/internal/elements/AbstractSequenceNode.java
- plugins/org.eclipse.sirius.diagram.sequence/src/org/eclipse/sirius/diagram/sequence/business/internal/elements/InstanceRole.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/api/image/WorkspaceImageHelper.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/internal/query/DNodeQuery.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/edit/api/part/AbstractDiagramBorderNodeEditPart.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/edit/internal/part/AbstractDiagramNodeEditPartRefreshVisualsOperation.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/edit/parts/AutoSizeNodeLayout.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/edit/parts/DNode2EditPart.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/edit/parts/DNode3EditPart.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/edit/parts/DNode4EditPart.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/edit/parts/DNodeEditPart.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/AbstractCanonicalSynchronizer.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/view/factories/AbstractDNodeViewFactory.java
- plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/business/internal/metamodel/helper/StyleHelper.java
- plugins/org.eclipse.sirius.doc/doc/specifier/diagrams/Diagrams.html
- plugins/org.eclipse.sirius.doc/doc/specifier/diagrams/Diagrams.textile
- plugins/org.eclipse.sirius.tests.junit/data/unit/layout/data/xmi/storedFormat-DiagType5__of__MyPackage.xmi
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/size/github-issue-65/github-issue-65.aird
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/size/github-issue-65/github-issue-65.ecore
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/size/github-issue-65/github-issue-65.odesign
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/SetStyleToWorkspaceImageTests.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/SizeComputationExpressionTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/InstanceRoleResizableEditPolicyTests.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/AllTestSuite.java
See issue #65 
The label of nodes is now properly displayed and the size of nodes increases with the size of the label.
> Handle auto size for nodes

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/actions/TabbarPasteFormatMenuManager.java
The correct code in dispose is `actionHistory = null`, not `actionHistory.clear()`. However, the GMF bug caused a premature dispose, resulting in an NPE. Now, the GMF bug has been fixed and the correct code can be restored without error.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/114
**Please do not merge this PR before the GMF 1.16.3 release (and the Sirius TP update).**
> [114] Adapts TabbarPasteFormatMenuManager dispose to a GMF bug fix

- releng/org.eclipse.sirius.targets/capella/sirius_2023-03.target
- releng/org.eclipse.sirius.targets/headless/sirius_2023-03.target
The target platform have been changed, but only the `.target` files have been regenerated. This PR regenerates targets `capella/sirius_2023-03.target` and `headless/sirius_2023-03.target`.
> [releng] Generate target definition file for TP in capella and headless

- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/ArrangeAllLinkedBorderedNodesLayoutStabilityTest.java
The test for Move Pinned Elements option changes a preference but does not restore its value at the end, which causes it to fail on its second run. This commit fixes this problem.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/141
> [141] Fix test for Move Pinned Elements option

- plugins/org.eclipse.sirius.diagram.ui/src/org/eclipse/sirius/diagram/ui/business/api/query/EditPartQuery.java
This commit fixes a bug in feature "Move Pinned Elements". Feature "Move Pinned Elements" must allow - during the layout algorithm - to move elements even if they are pinned, but must still leave fixed the elements indicated as fixed in the algorithm parameters.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/141
> [141] Fix a bug in "Move Pinned Elements" with elements not to be moved

- plugins/org.eclipse.sirius.tests.swtbot.support/pom.xml
- plugins/org.eclipse.sirius.tests.swtbot/pom.xml
SWTBot execution on CI fails due to
java.lang.NoClassDefFoundError: org/apache/log4j/Logger
No error in PR 
https://ci.eclipse.org/sirius/job/sirius-pr-check/job/mpo%252Freleng%252Flog4jasExttraReqForTestsCITrial/lastCompletedBuild/testReport/org.eclipse.sirius.tests.swtbot/
> [releng] Add Log4j in extra requirements to avoid error in CI tests

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/preferences/DiagramGeneralPreferencePage.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/192
> [192] Set the preference to mark moved items as pinned false by default

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/api/view/SiriusLayoutDataManager.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/internal/view/SiriusLayoutDataManagerImpl.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/AbstractCanonicalSynchronizer.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/layout/SiriusCanonicalLayoutCommand.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/layout/SiriusCanonicalLayoutHandler.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/layout/provider/DefaultLayoutProvider.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/DOperationHistoryListener.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/layout/provider/BorderItemAwareLayoutProvider.java
- plugins/org.eclipse.sirius.doc/doc/Release_Notes.html
- plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/borderNodeSide/github-issue-145/github-issue-145.aird
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/borderNodeSide/github-issue-145/github-issue-145.ecore
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/borderNodeSide/github-issue-145/github-issue-145.odesign
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/LinkedBorderNodeLocationTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/AllTestSuite.java
See issue #145
When a node with linked border node is updated (drag and drop, refresh unsynchronized element, custom creation tool...), its linked border nodes is not properly laid out. An "Arrange" command is executed but border nodes are not arranged.
Scenario in the image: Drag and drop "SubEPackage1" from EPackage6 to EPackage1.
Before fix:
After fix:
> [145] Arrange linked border nodes when updating their container

- Jenkinsfile
It looks like concurrent executions of the job combined with parallel sub-stages can cause deadlocks when too many PRs are checked in parallel for the limited number of executors we have.
> [releng] Disable concurrent executions of the sirius-pr-check jobs

- releng/org.eclipse.sirius.targets/capella/sirius_2023-03.target
- releng/org.eclipse.sirius.targets/capella/sirius_2023-03.targetplatform
- releng/org.eclipse.sirius.targets/headless/sirius_2023-03.target
- releng/org.eclipse.sirius.targets/headless/sirius_2023-03.targetplatform
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/203
> [203] Upgrade to ELK 0.9.0 fo missed target platforms

- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/editor/vsm/LayoutOptionsTests.java
The test org.eclipse.sirius.tests.swtbot.editor.vsm.LayoutOptionsTests.testLayoutOptionModifications() has an hardcoded value of the number of options. As the ELK version has been changed, it is expected to have new options.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/203
> [203] Fix test according to upgrade of ELK to 0.9.0 version

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/render/SiriusGraphicsToGraphics2DAdaptor.java
https://github.com/eclipse-sirius/sirius-desktop/issues/238
> Fix miter-limit of Stroke in SVG export.

- plugins/org.eclipse.sirius.tests.swtbot.support/src/org/eclipse/sirius/tests/swtbot/support/api/AbstractSiriusSwtBotGefTestCase.java
`clearAllFields` must be executed after `checkLogs`, otherwise the logs are null and there are no more logs to check.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/144
> [144][test] Fix an NPE in the unreliable collab tests

- Jenkinsfile
When several PRs are pushed simultaneously, each PR can occupy part of the 4 free slots. So parallel sub-stages can take several minutes to actually start (even if the timeout starts at the start of the "parent" stage).
FYI, a timeout already exists individually on each sub-stage (currently set at 2 hours).
> [releng] Remove global 1 hour timeout

- Jenkinsfile
This option has been added in commit 5b7db7fe [1] to try to disable concurrent executions of pull request's jobs. In fact, it only avoids the concurrent execution of two jobs of the same PR, which was not the desired objective. Another solution was found (via commit 967b6e6b [2]). This option can therefore be removed.
[1] https://github.com/eclipse-sirius/sirius-desktop/commit/5b7db7fefafd964e3b6f95ac32cd376a2caa670f
[2] https://github.com/eclipse-sirius/sirius-desktop/commit/967b6e6bf73aeb1f4d4ede8b6d5195f041c16c50
> [releng] Remove disableConcurrentBuilds option

- releng/org.eclipse.sirius.targets/capella/sirius_2023-03.target
- releng/org.eclipse.sirius.targets/headless/sirius_2023-03.target
- releng/org.eclipse.sirius.targets/modules/gmf-runtime-1.16.tpd
- releng/org.eclipse.sirius.targets/sirius_2022-09.target
- releng/org.eclipse.sirius.targets/sirius_2022-12.target
- releng/org.eclipse.sirius.targets/sirius_2023-03.target
- releng/org.eclipse.sirius.targets/sirius_2023-06.target
- releng/org.eclipse.sirius.targets/sirius_2023-09.target
It contains dependency to repackaged batik that prevent loading too much bundle (remove "Eclipse-BuddyPolicy: dependent" usage)
Change-Id: If9f67198854b97fc343729ec27ea884dda3a98b5
> [releng] Update TPs to gmf-runtime milestone S202401081627

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/api/view/SiriusLayoutDataManager.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/internal/view/SiriusLayoutDataManagerImpl.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/AbstractCanonicalSynchronizer.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/CanonicalSynchronizerResult.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/diagram/DDiagramCanonicalSynchronizer.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/layout/SiriusCanonicalLayoutCommand.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/layout/SiriusCanonicalLayoutHandler.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/LinkedBorderNodeLocationTest.java
When an element is moved within the model, the layout of its contents remains unchanged, with the exception of border nodes.
This commit adds automatic border node layout for elements on the diagram background and fixes some bugs.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/145
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/244
> [244][145] keep layout when moving an element in model

- packaging/org.eclipse.sirius.parent/pom.xml
In console of sirius.sonar.job we can see some errors as : 20:27:27 [ERROR] Unable to parse source file :
'plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/layout/LayoutChildrenTest.java' 20:27:27 [ERROR] Parse error at line 151 column 8: Arrow in case statement supported from Java 14 onwards only
Indeed, in the configuration, the parameter `sonar.java.source` is always 8, instead of 17 (according to the "recent" change).
> [releng] Switch to java 17 in Sonar Analysis

- packaging/org.eclipse.sirius.parent/pom.xml
In SonarCloud [1], a message says `Specifying module-relative paths at project level in the property 'sonar.exclusions' is deprecated. To continue matching files like
'plugins/org.eclipse.sirius.diagram.formatdata/src-gen/org/eclipse/sirius/diagram/formatdata/AbstractFormatData.java', update this property so that patterns refer to project-relative paths.`
This commit tries to fix this problem.
[1] https://sonarcloud.io/code?id=org.eclipse.sirius
> [releng] Update sonar.exclusions parameter according to warning message

- packaging/org.eclipse.sirius.parent/pom.xml
Try to improve Sonar configuration according to messages logged in console of job "sirius.sonar-master" [1] and also in SonarCube ("The last analysis has warnings. See details") [2].
Currently "fixed" in this commit:
* [WARNING] Property 'sonar.jacoco.reportPath' is no longer supported. Use JaCoCo's xml report and sonar-jacoco plugin.
* [WARNING] Property 'sonar.jacoco.itReportPath' is no longer supported. Use JaCoCo's xml report and sonar-jacoco plugin.
* Error while running Node.js. A supported version of Node.js is required for running the analysis of JS in HTML files. Please make sure a supported version of Node.js is available in the PATH. Alternatively, you can exclude JS in HTML files from your analysis using the 'sonar.exclusions' configuration property.
* "it configurations", for …
> [releng] Update Sonar configuration

- packaging/org.eclipse.sirius.parent/pom.xml
- plugins/org.eclipse.sirius.tests.sample.component.design/pom.xml
- plugins/org.eclipse.sirius.tests.sample.docbook.design/pom.xml
- plugins/org.eclipse.sirius.tests.sample.migration.design/pom.xml
- plugins/org.eclipse.sirius.tests.sample.scxml.design/pom.xml
- plugins/org.eclipse.sirius.tests.sample.xtext.statemachine.design/pom.xml
- plugins/org.eclipse.sirius.tests.sample.xtext.statemachine.ide/pom.xml
- plugins/org.eclipse.sirius.tests.sample.xtext.statemachine.ui/pom.xml
- plugins/org.eclipse.sirius.tests.sample.xtext.statemachine/pom.xml
Tests plug-ins, which have `<packaging>eclipse-test-plugin</packaging>` in there pom.xml file, are automatically excluded from code coverage analysis (as said in SonarCloud doc [1]). So the configuration `<sonar.coverage.exclusions>...,${project.basedir}/../../plugins/org.eclipse.sirius.tests*/**/*.java</sonar.coverage.exclusions>` does not seems relevant. I left it for now. If my analysis is correct, the parameter
`<sonar.coverage.exclusions>src/**/*</sonar.coverage.exclusions>` in all tests plug-ins is also to be remved (to see later).
Globally, the parameter `<sonar.coverage.exclusions>` seems to be used to exclude specific files or directories from coverage analysis, not entire modules. This would explain why all plug-in starting with "org.eclipse.sirius.sample*" are currently not …
> [releng] Update Sonar configuration - Improve exclusion of code coverage

- plugins/org.eclipse.sirius.tests.junit.support/pom.xml
- plugins/org.eclipse.sirius.tests.junit.xtext/pom.xml
- plugins/org.eclipse.sirius.tests.junit/pom.xml
- plugins/org.eclipse.sirius.tests.swtbot.support/pom.xml
- plugins/org.eclipse.sirius.tests.swtbot/pom.xml
- plugins/org.eclipse.sirius.tests.tree/pom.xml
- plugins/org.eclipse.sirius.tests.ui.properties/pom.xml
The last commit [1], `[releng] Remove unnecessary
"sonar.coverage.exclusions" parameters`, reveals that these parameters were useful. Indeed, the code of tests is now wrongly considered in coverage result.
This commit tries to disable this, by using explicit "sonar.tests" parameter. I thought that it is automatically set according to "<packaging>eclipse-test-plugin</packaging>" parameter as shown in documentation [2].
[1] https://github.com/eclipse-sirius/sirius-desktop/commit/d8577f7dd7e06675fc9d070e15a43ac742d0b026
[2] https://docs.sonarsource.com/sonarcloud/advanced-setup/analysis-scope/#automatic-setting-for-maven-gradle-and-net
> [releng] Explicitly set tests code for Sonar analysis

- plugins/org.eclipse.sirius.sample.ecore.design/pom.xml
- plugins/org.eclipse.sirius.sample.interactions.design/pom.xml
- plugins/org.eclipse.sirius.sample.interactions.edit/pom.xml
- plugins/org.eclipse.sirius.sample.interactions.editor/pom.xml
- plugins/org.eclipse.sirius.sample.interactions/pom.xml
- plugins/org.eclipse.sirius.sample.properties.checkbox/pom.xml
- plugins/org.eclipse.sirius.sample.properties.radio/pom.xml
- plugins/org.eclipse.sirius.sample.properties.textarea/pom.xml
- plugins/org.eclipse.sirius.sample.properties/pom.xml
- plugins/org.eclipse.sirius.samples.family/samples/org.eclipse.sirius.sample.basicfamily.design/pom.xml
- plugins/org.eclipse.sirius.samples.family/samples/org.eclipse.sirius.sample.basicfamily.edit/pom.xml
- plugins/org.eclipse.sirius.samples.family/samples/org.eclipse.sirius.sample.basicfamily.editor/pom.xml
- plugins/org.eclipse.sirius.samples.family/samples/org.eclipse.sirius.sample.basicfamily/pom.xml
- plugins/org.eclipse.sirius.tests.sample.benchmark/pom.xml
- plugins/org.eclipse.sirius.tests.sample.component.design/pom.xml
- plugins/org.eclipse.sirius.tests.sample.component/pom.xml
- plugins/org.eclipse.sirius.tests.sample.docbook.design/pom.xml
- plugins/org.eclipse.sirius.tests.sample.docbook.edit/pom.xml
- plugins/org.eclipse.sirius.tests.sample.docbook.editor/pom.xml
- plugins/org.eclipse.sirius.tests.sample.docbook/pom.xml
- plugins/org.eclipse.sirius.tests.sample.migration.design/pom.xml
- plugins/org.eclipse.sirius.tests.sample.migration/pom.xml
- plugins/org.eclipse.sirius.tests.sample.scxml.design/pom.xml
- plugins/org.eclipse.sirius.tests.sample.scxml/pom.xml
- plugins/org.eclipse.sirius.tests.sample.xtext.statemachine.design/pom.xml
- plugins/org.eclipse.sirius.tests.sample.xtext.statemachine.ide/pom.xml
- plugins/org.eclipse.sirius.tests.sample.xtext.statemachine.ui/pom.xml
- plugins/org.eclipse.sirius.tests.sample.xtext.statemachine/pom.xml
Before this commit, only a part of plug-ins "org.eclipse.sirius.sample*" is excluded of code coverage by Sonar.
The goal of this commit is to cosier all plug-ins
"org.eclipse.sirius.sample*" and "org.eclipse.sirius.tests.sample*" as tests code and by consequence excluded from Sonar code coverage analysis.
> [releng] Consider all "sample" plug-ins as tests code

- plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/business/internal/dialect/DiagramDialectServices.java
- plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/diagram/outline/OutlineContextualMenuTest.java
With the last commit [1] concerning this issue, too much views are considered as to be centered. This leads to a memory leak. Indeed, SiriusLayoutDataManagerImpl.addCreatedViewForInitPositionLayout(Diagram, LinkedHashSet<View>) was called, but
SiriusLayoutDataManagerImpl.removeLayoutViews(Diagram) was not call.
The condition `SiriusLayoutDataManager.INSTANCE.getData().some()` existing before the commit [1] is added again.
[1] https://github.com/eclipse-sirius/sirius-desktop/commit/b8a5c6a9d0888e4f26a99210f70bd247a9981c51
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/18
> [18] Avoid to consider too much views as to be centered

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/layout/PasteStylePureGraphicalAction.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/pinning/PinElementsAction.java
A first preventive fix was made in commit
2ccb31c44715da9c89af6ed080b1e671d845f260 by changing listeners of PinElementsAction and PasteStylePureGraphicalAction to update their action state with a displaySyncExec call instead of a displayAsyncExec in order to prevent the action from being disposed of due to an asynchronous call.
In the commit complete the preventive with a better handling of potentially null active page.
Change-Id: I04232b9626c7fb2a0cbf992fad8339bd2fdd5da0
> [205] Complete anti NPEs fix

- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/TabBarTest.java
New actions have been added in Tabbar through issue #205, this changes the expected values in TabBarTest.
> [205] Fix tests

- plugins/org.eclipse.sirius.common/src/org/eclipse/sirius/common/tools/api/util/StringMatcher.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/graphical/edit/policies/AirXYLayoutEditPolicy.java
- plugins/org.eclipse.sirius.model/src/org/eclipse/sirius/model/business/internal/query/EObjectQuery.java
- plugins/org.eclipse.sirius.table.ui/src-paperclips/org/eclipse/sirius/table/ui/tools/internal/paperclips/grid/internal/GridIterator.java
- plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/api/session/DAnalysisSessionTests.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/DiagramMouseZoomTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/CombinedFragmentsDisabledTests.java
- plugins/org.eclipse.sirius.ui/src/org/eclipse/sirius/ui/tools/api/actions/export/ExportAction.java
* AirXYLayoutEditPolicy: Fix this call that leads to an illegal type cast.
* CombinedFragmentsDisabledTests and DiagramMouseZoomTest: Change the assertion arguments to not compare dissimilar types.
* DAnalysisSessionTests: Don't use assertEquals() inside a try-catch catching an AssertionError.
* EObjectQuery: Fix this illegal type cast.
* ExportAction: Remove this throw statement from this finally block.
* GridIterator: Make sure "totalWeight" can't be zero before doing this division.
* StringMatcher: Fix this access on a collection that may trigger an 'ArrayIndexOutOfBoundsException'.
> [cleanup] Fix the 9 Sonar Critical bugs

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/dialogs/ColorPaletteComposite.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/dialogs/ColorPalettePopup.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/actions/ColorPropertyContributionItem.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/properties/DiagramColorAndFontPropertySection.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/properties/DiagramConnectionAppearancePropertySection.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/properties/DiagramShapeColorAndFontPropertySection.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/properties/LabelColorAndFontPropertySection.java
- The top-left location of the ColorPalettePopup is computed to fully display the popup when buttons from the toolbar or appearance tab are close to the edge of the window.
- Set a default width for the ColorPaletteComposite when it is empty
Change-Id: I1246641707437ab3574546d31b5da38d55fcef0a
> [152] Compute the location of the ColorPalettePopup

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/actions/ColorPropertyContributionItem.java
Otherwise the first time the user clicks on the button (which seems
like the most obvious thing to do to change a color) does nothing at
all.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/152
> [152] Open the color popup if no previous color is set

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/format/AbstractSiriusFormatDataManager.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/format/BasicSiriusStyleApplicator.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/format/SiriusStyleApplicator.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/commands/PasteStyleCommandProvider.java
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/490444.aird
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/490444.ecore
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/PasteStylePureGraphicalTest.java
The commit also create SiriusStyleApplicator to share the style application with the semantic paste style while keeping the API for the semantic paste style and allowing code extensibility for paste style.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/321
> [321] Add custom feature on the paste style to avoid undo on refresh

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/format/SiriusStyleApplicator.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/PasteStylePureGraphicalTest.java
When copying the style from a node to a container with gradient style, now, the foreground and the background colors are changed.
https://github.com/eclipse-sirius/sirius-desktop/issues/346
> [346] Make "Paste Style" colorize fully the gradient style

- plugins/org.eclipse.sirius.ui/src/org/eclipse/sirius/ui/business/internal/session/EditingSession.java
Created from [Capella issue 2860](https://github.com/eclipse-capella/capella/issues/2860).
Not reproduced with Sirius alone for now.
Current steps to reproduce are listed in comment https://github.com/eclipse-capella/capella/issues/2860#issuecomment-2074824537
> #372 Avoid NPEs while closing projects from repair / migration with "other" projects opened and modified diagram editor

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/palette/SiriusSelectionToolEx.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/ui/SnapToAllDragEditPartsTracker.java
- plugins/org.eclipse.sirius.ext.gmf.runtime/src/org/eclipse/sirius/ext/gmf/runtime/editparts/GraphicalHelper.java
- plugins/org.eclipse.sirius.tests.swtbot.support/src/org/eclipse/sirius/tests/swtbot/support/api/condition/CheckBoundsCondition.java
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/snap/representations.aird
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/MoveAllShapesWithArrowKeysTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/SnapAllShapesTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/AllTestSuite.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/359
> [359] New implementation of move with arrow keys

- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/SetStyleToWorkspaceImageTests.java
Some tests from
org.eclipse.sirius.tests.swtbot.SetStyleToWorkspaceImageTests copy an image to the clipboard but do not clean it after the test. This could have side effects on the following tests.
This was the case in some tests of TabBarTest that failed in the suite org.eclipse.sirius.tests.swtbot.suite.AllUnreliableTestSuite because SetStyleToWorkspaceImageTests is executed before TabBarTest.
> [205] Correctly clean clipboard from SetStyleToWorkspaceImageTests

- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/AllUnreliableTestSuite.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/TabBarTest.java
The tests from TabBarTest are no longer unreliable.
> [test] Remove tests from TabBarTest as unreliable

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/AbstractMenuContributionItem.java
When the VSM is changed, the tooltip of all layers is updated. But the tooltip list was never cleared between two menuShow. So the first N tooltip text (with N, the number of layers) were always the same and the updated tooltip were in an unreachable position (at the end) in the list.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/362
> [362] Fix the bug in the refresh of the layer tooltip

- plugins/org.eclipse.sirius.tests.swtbot.support/src/org/eclipse/sirius/tests/swtbot/support/api/AbstractSiriusSwtBotGefTestCase.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/EdgeLabelStabilityTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/layout/BorderedNodeCopyPasteFormatTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/layout/ContainerAndNodeCopyPasteFormatTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/layout/EdgeCopyPasteFormatTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/layout/EdgeStabilityOnCopyPasteLayoutTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/PasteStylePureGraphicalTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/uml/CopyPasteFormatOfLabelOfBorderedNodeTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/uml/CopyPasteLayoutOfPortsWithConflictWithNotPastedPortsTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/uml/CopyPasteLayoutOfPortsWithConflictWithPastedPortsTest.java
Some tests do not clear the FormatDataManager after using Copy/Paste actions. This causes some side effects on other tests (tests from TabBarTest for example).
> [test] Clear FormatDataManager after using Copy/Paste actions

- plugins/org.eclipse.sirius.tests.swtbot.support/src/org/eclipse/sirius/tests/swtbot/support/api/condition/OperationDoneCondition.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/AbstractRefreshWithCustomizedStyleOnCompleteExampleTest.java
Tests from RefreshWithCustomizedStyleTests fail on some CI servers. It seems that the field is not "validated" and the model/session is not modified.
This commit adds several conditions to make tests more reliable:
- a "traverse" call for text fields to force the validation for this kind of field,
- the Properties view is maximized before setting fields. At least the modification of a combo box can be problematic on Linux if the field is not "visible",
- a condition, OperationDoneCondition, has been added. This allows to have a better feedback in case of failure,
- several "SWTBotUtils.waitAllUiEvents();" have been added.
> [test] Fix RefreshWithCustomizedStyleTests

- plugins/org.eclipse.sirius.ui/plugin.xml
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/368
> [368] Fix model explorer labels for JDT elements

- plugins/org.eclipse.sirius.ui/plugin.xml
- plugins/org.eclipse.sirius.ui/src/org/eclipse/sirius/ui/tools/internal/views/common/navigator/SiriusCommonLabelProvider.java
Do not look for elements adapted as IProject in calls to sessionLabelProvider::getText/getImage
PossibleChildren / TriggerPoint expressions evaluation change with 2023-03 for some JDT elements
See result of
org.eclipse.ui.internal.navigator.extensions.NavigatorContentDescriptorManager.findDescriptors for org.eclipse.jdt.internal.core.PackageFragmentRoot or org.eclipse.jdt.internal.core.JrtPackageFragmentRoot which are now adaptable into IProject and are displayed in a EcoreModelingProject for example: src folder, JRE System library modules.
Re-add " appearsBefore="org.eclipse.jdt.java.ui.javaContent" to have "*" displayed in project text for ModelingProject with dirty session status when org.eclipse.sirius.ui.business.api.preferences.SiriusUIPreferencesKeys.PREF_SAVE_WHEN_NO_EDITOR is set …
> [419] Exclude adapted IProject elements from sessionLabelProvider calls

- plugins/org.eclipse.sirius.diagram.ui/plugin.xml
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/part/DDiagramEditorActionBarContributor.java
- plugins/org.eclipse.sirius.sample.ecore.design/META-INF/MANIFEST.MF
- plugins/org.eclipse.sirius.sample.ecore.design/plugin.xml
- plugins/org.eclipse.sirius.sample.ecore.design/src/org/eclipse/sirius/sample/ecore/design/editor/ui/part/EcoreEntitiesActionBarContributor.java
- plugins/org.eclipse.sirius.tests.junit.xtext/pom.xml
- plugins/org.eclipse.sirius.tests.junit/pom.xml
- plugins/org.eclipse.sirius.tests.swtbot/pom.xml
- plugins/org.eclipse.sirius.tests.tree/pom.xml
- plugins/org.eclipse.sirius.tests.ui.properties/pom.xml
This PR follows PR #175.
Create a specific ActionBarContributor for each specific implementation of SiriusDiagramEditor to avoid a duplication of ActionRegistry: one for "SiriusDiagramEditor.class" and one for real implementation ("DDiagramEditorImpl.class" or "EcoreEntitiesReadOnlyEditor.class"). Indeed, only one of the ActionRegistry is correctly cleaned at the closing of the editor.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/176
> [176] Adapt SiriusDiagramActionBarContributor to avoid memory leak

- plugins/org.eclipse.sirius.diagram.ui/src/org/eclipse/sirius/diagram/ui/internal/layout/GenericLayoutProvider.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/356
> [356] Fix Optional.orElseGet(null) leading to systematic error

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/palette/PaletteManagerImpl.java
Since enhancement #428, the test
PaletteViewManagementTest.testOpenPaletteOpenTwoDiagram() fails in tiemout. This commit fixes this problem.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/428
> [428] Fix PaletteViewManagementTest regression

- plugins/org.eclipse.sirius.diagram.sequence.ui/src/org/eclipse/sirius/diagram/sequence/ui/tool/internal/edit/operation/SequenceEditPartsOperations.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/internal/view/SiriusLayoutDataManagerImpl.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/edit/internal/part/DiagramEdgeEditPartOperation.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/SiriusRulerEditPartFactory.java
The recent changes in question are:
* https://github.com/eclipse/gef-classic/commit/e5d6bac76ff38625b7c04877c0582452f04055ff#diff-07534b33eaa5ec93832be67ba799518320ca49589ed53976a24a66481e54e36e which changes the return type of `EditPartView.getEditPartRegistry()` from a plain/untyped `Map` into a `Map<Object, EditPart>`. The adaptation is trivial.
* https://github.com/eclipse/gef-classic/commit/4fce72b354db7af98cdb169d19b785a362560c81#diff-e157353a244e432d229f6caf980c2d097558bdd72baf4d3f9beb1d3162ec8bb3 is slightly more subtle as it removes a `protected` method we used to override (`createRulerEditPart`). To get a version which works with both old and new GEF versions, we now override the whole `createEditPart()` method instead. Hopefully its definition in GEF will not change in ways …
> [341] Adapt to recent GEF Classic changes

- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/modelexplorer/LockedModelExplorerTest.java
The test "testRefreshJobForModelExplorerView()" of "org.eclipse.sirius.tests.swtbot.modelexplorer.LockedModelExplorerTest" has failed at least once on a CI server with this stack:
```
junit.framework.AssertionFailedError: The job should be scheduled as one
lock notification has been send and ModelExplorer view is opened.
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.sirius.tests.swtbot.modelexplorer.LockedModelExplorerTest.testRefreshJobForModelExplorerView(LockedModelExplorerTest.java:132)
```
Maybe the job has not been scheduled before test on "refreshJobScheduled". The "wait until condition" should solve this random case.
> [test] Fix unreliable LockedModelExplorerTest

- plugins/org.eclipse.sirius.tests.junit.support/src/org/eclipse/sirius/tests/support/api/SiriusTestCase.java
- plugins/org.eclipse.sirius.tests.swtbot.support/src/org/eclipse/sirius/tests/swtbot/support/api/AbstractSiriusSwtBotGefTestCase.java
This commit improves the preference change methods, so that it can be called several times without any problem to restore the initial value.
> [test] improves the restoration of preferences in the test

- plugins/org.eclipse.sirius.tests.junit.support/src/org/eclipse/sirius/tests/support/api/SiriusTestCase.java
Some tests fail since the commit dc87bccb "[test] improves the restoration of preferences in the test
" [1]. Its goals was to allow better restoration of the initial preference values when using "changeXXXPreference" methods of SiriusTestCase or AbstractSiriusSwtBotGefTestCase superclasses. The side effect is that some tests were OK before because they relied on "wrong" default values ​​for some preferences.
Previous commits try to fix tests one by one. But some of them are unreliable. It seems that the SaveSessionJob, launched randomly, can have several effects. So a drastic solution is to set the preference SiriusUIPreferencesKeys.PREF_SAVE_WHEN_NO_EDITOR to false by default for all Junit tests. The preference PREF_RELOAD_ON_LAST_EDITOR_CLOSE is also set to false (as explained in the …
> [test] Set PREF_SAVE_WHEN_NO_EDITOR to false by default for JUnit tests

- plugins/org.eclipse.sirius.diagram.ui/plugin.properties
- plugins/org.eclipse.sirius.diagram.ui/plugin.xml
- plugins/org.eclipse.sirius.diagram.ui/schema/colorPalettePopupProvider.exsd
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/color/ColorPalettePopupProvider.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/color/ColorPalettePopupService.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/color/DefaultColorPalettePopupProvider.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/color/IColorPalettePopup.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/dialogs/ColorPalettePopup.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/editor/tabbar/actions/ColorPropertyContributionItem.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/properties/DiagramColorAndFontPropertySection.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/properties/DiagramConnectionAppearancePropertySection.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/properties/DiagramShapeColorAndFontPropertySection.java
- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/properties/LabelColorAndFontPropertySection.java
A new Eclipse extension point
"org.eclipse.sirius.diagram.ui.colorPalettePopupProvider" has been added to handle a flexible provider mechanism for IColorPalettePopup. The default provider DefaultColorPalettePopupProvider is used if no custom providers are registered, allowing customization of the color palette popup.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/460
> [460] Add extension point for color palette popup providers

- plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/business/internal/helper/task/CreateDEdgeTask.java
- plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/business/internal/sync/DDiagramSynchronizer.java
Bug: #467 
Fix regressions introduced with #470 :
- Regression identified in
- HideRevealEdgeLabelsTest
- EdgeCreationPositionTest
- EdgeCreationPositionWithSnapToGridTest
- EdgeWithBorderNodeCreationPositionWithSnapToGridTest
- The provided fix does not handle the extra mapping cases (edge tool creation two border nodes + an edge for example)
- completing the introduced validation on  source/target would be touchy : extra mappings, mappings imports, complex structure created by tools.
- The validation of the createDEdgeTask which automatically creates an edge from the EdgeCreationTool should check the semanticElement of the edgeCandidates rather than the correspondance of the clicked sourceView/targetView and the candidate sourceView/targetView.
The idea of the new fix is not follow the …
> [467] Fix edge creation tool regressions

- plugins/org.eclipse.sirius.sample.interactions.design/description/interaction.odesign
"Force refresh" avoids the potential bug seen in this issue, even though "auto-refresh" is, in theory, a requirement for sequence diagram.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/527
> [527] Add a "force refresh" for Combined Fragment create tool

- plugins/org.eclipse.sirius.diagram.sequence/src/org/eclipse/sirius/diagram/sequence/business/internal/layout/horizontal/SequenceHorizontalLayout.java
- plugins/org.eclipse.sirius.diagram.sequence/src/org/eclipse/sirius/diagram/sequence/business/internal/layout/vertical/SequenceVerticalLayout.java
- plugins/org.eclipse.sirius.tests.swtbot/data/unit/sequence/navigation/fixture.aird
This PR rework the layout computation for InteractionContainer and handle additional cases
- When a group of execution is present on the right lifeline, the depth of excution and their width is taken into account to compute the InteractionContainer width 
- The vertical layout of InteractionContainer has also been reworked to be based on the currently computed "future range" of lifelines and add the current margin:
----
Edit : this last part has been removed from this PR
- The InteractionContainer is not always placed at (0,0) but follows the moves of the first left InstanceRole:
This makes the reset Origin works in standard way, the arrange all too. It also gve the possibility to the user to easily select the diagram background to get the "diagram" tabbar
> #518 Improve InteractionContainer layout

- plugins/org.eclipse.sirius.diagram.sequence/src/org/eclipse/sirius/diagram/sequence/business/internal/layout/horizontal/SequenceHorizontalLayout.java
Layout the InteractionContainer x instead of being always at (0,0). Also allows to easily keep a left margin to be able to select the diagram background
Can be enabled with
-Dorg.eclipse.sirius.diagram.sequence.layout.interaction.container.dynamic.left=true
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/518
> #518 Add capability to have InteractionContainer left border dynamically layouted (and not always on 0,0)

- plugins/org.eclipse.sirius.diagram.sequence.ui/src/org/eclipse/sirius/diagram/sequence/ui/tool/internal/edit/validator/ISEComplexMoveValidator.java
Final moved range was not updated after each query update. This used to cause wrong identification of message to reconnect and incorrect vertical layout (no conservation of unmoved message positions) after some execution moves with the target final range engloing unmoved simple messages.
> [536] Fix ISEComplexeMoveValidator re-initialization

- plugins/org.eclipse.sirius.diagram.sequence.ui/src/org/eclipse/sirius/diagram/sequence/ui/tool/internal/edit/policy/ExecutionSelectionEditPolicy.java
- plugins/org.eclipse.sirius.diagram.sequence.ui/src/org/eclipse/sirius/diagram/sequence/ui/tool/internal/edit/validator/ISEComplexMoveValidator.java
- plugins/org.eclipse.sirius.diagram.sequence/src/org/eclipse/sirius/diagram/sequence/tool/internal/validation/description/constraints/UniqueInteractionContainerMappingConstraints.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/AbstractDefaultModelSequenceTests.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/AbstractSequenceDiagramTestCase.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/ObservationPointTests.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/SequenceExecutionBasicAndReturnMessageObervationPointDisplayedTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/SequenceExecutionBasicAndReturnMessageTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/SequenceSwtBotTestSuite.java
Final moved range was not updated after each query update. This used to cause wrong identification of message to reconnect and incorrect vertical layout (no conservation of unmoved message positions) after some execution moves with the target final range engloing unmoved simple messages.
> [536] Fix Execution resize/move operations 

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/figure/DiagramSemanticElementLockedNotificationFigure.java
Change-Id: Id08e5887d559a29391eacd016b54cb35343c47ed
> [cleanup] Remove unused and infinite loop designed method

- Jenkinsfile
- packaging/org.eclipse.sirius.parent/pom.xml
- plugins/org.eclipse.sirius.tests.junit/data/unit/migration/do_not_migrate/VP-4169/VP-4169.aird
- plugins/org.eclipse.sirius/src/org/eclipse/sirius/business/internal/migration/RepresentationsFileMigrationService.java
To support Java21, that is now [1] used to build Sirius, we need at least Jacoco 0.8.9.
[1] https://github.com/eclipse-sirius/sirius-desktop/commit/054f30ce4de5518ef9852d7a30361a985d8f2548
> [releng] Fix some problems detected on CI server

- plugins/org.eclipse.sirius.editor.diagram/plugin.xml
- plugins/org.eclipse.sirius.editor.tree/plugin.xml
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/editor/vsm/AbstractContentAssistTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/editor/vsm/CompletionProposalInVSMTest.java
Replace afterSection="style.section.labelStyleDescription.LabelColor" by afterSection="style.section.basicLabelStyleDescription.LabelColor"
The problem has been discovered since the commit [1] and the change of Tycho version. When launching tests with this version of Tycho some tests of TreeItemStyleDescriptionTest fail. The order of plugin.xml loading seems to be change and it reveal the problem that exist since a long time.
Observed problem: the property "Label Color" is displayed after the property "Background Color".
[1] https://github.com/eclipse-sirius/sirius-desktop/commit/08fb66d1d934bb7fa98329c42e21087bcc84306c
> [fix] Replace wrong id for afterSection concerning label color

- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/AllTestSuite.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/AllUnreliableTestSuite.java
On CI server, the SwtBot suite regularly fails on ArrangeAllTest or ArrangeAllWithSnapToGridTest due to "Pango Error". In this condition, there was no result for the corresponding job.
The goal of this commit is to allow to exclude these tests to have the result for the other tests.
> [test] Add ArrangeAll*Test as unreliable

- plugins/org.eclipse.sirius.diagram.sequence/src/org/eclipse/sirius/diagram/sequence/business/internal/layout/vertical/SequenceVerticalLayout.java
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3478
This pattern was wrongly allowed before, but with ecj from 2025-03
it (correctly) causes a compilation error.
> [fix] Fix compilation error when using Eclipse 2025-03

- plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/listeners/FontFormatUpdater.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/AbstractRefreshWithCustomizedStyleTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/BoldItalicFontSynchronizationTest.java
- plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/LabelFontModificationsTest.java
This commit also refactor class FontFormatUpdater and update the tests to check also the edge labels.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/584
> [584] Fix bug on the edge label font size after refresh

- plugins/org.eclipse.sirius.diagram.sequence.ui/src/org/eclipse/sirius/diagram/sequence/ui/business/api/diagramtype/SequenceDiagramTypeProvider.java
- plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/diagram/sequence/NewChildMenusExtensionTests.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/590
Change-Id: Ibf6762095e18a84d88294af08a14170a9d6e9da1
> [590] Remove not handled mappings from layers children creation menu
