eclipse-sirius/sirius-desktop

releng/org.eclipse.sirius.targets/capella/sirius_2023-03.target, releng/org.eclipse.sirius.targets/capella/sirius_2023-03.targetplatform, releng/org.eclipse.sirius.targets/headless/sirius_2023-03.target, releng/org.eclipse.sirius.targets/headless/sirius_2023-03.targetplatform
Change-Id: I23638df1ebffe3d41321424748824ef384c49448
=> [releng] Update Sirius TPs to GMF-runtime 1.16 (part2)

Jenkinsfile
=> [releng] Setup a minimal Jenkinsfile

Jenkinsfile, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/AllTestSuite.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/SequenceSwtBotTestSuite.java
=> [releng] Launch 'gerrit' test suites to validate PRs

plugins/org.eclipse.sirius.tests.swtbot/data/unit/propertypage/My.interactions, plugins/org.eclipse.sirius.tests.swtbot/data/unit/propertypage/representations.aird, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/propertypage/SiriusSessionDetailsPropertyPageTest.java, plugins/org.eclipse.sirius/src/org/eclipse/sirius/business/internal/query/SessionDetailsReport.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/26
=> [26] Correctly identify Sequence diagram in Sirius Session Details

plugins/org.eclipse.sirius.doc/doc/Release_Notes.html, plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile
=> [doc] Add (empty) release notes section for 7.2.1

Jenkinsfile
=> [releng] Increase the test suites timeout

plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/common/migration/AbstractMigrationTestCase.java, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/common/migration/DiagramMigrationTestCampaign02.java, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/common/migration/DiagramMigrationTestCampaign09.java
Change-Id: I0a86101db980a7d562775f2ade01c5c9b0520f1b
=> [tests] Fix junit tests

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/listeners/FontFormatUpdater.java, plugins/org.eclipse.sirius.tests.swtbot/data/unit/style/customizations/My.odesign
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/91
=> [91] Fix the reset style button which was always disabled on edges.

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/listeners/FontFormatUpdater.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/AbstractRefreshWithCustomizedStyleTest.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/LabelFontModificationsTest.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/91
=> [91] Fix custom feature label format bug on edges.

packaging/org.eclipse.sirius.parent/pom.xml
The modified pom.xml in the previous commit was not the right one.
=> [test] Temporarily set Xmx to 3072m instead of 2048m - Round 2

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/util/EditPartQuery.java
=> [cleanup] Remove unused import

releng/org.eclipse.sirius.targets/modules/gmf-runtime-1.16.tpd, releng/org.eclipse.sirius.targets/sirius_2022-09.target, releng/org.eclipse.sirius.targets/sirius_2022-12.target, releng/org.eclipse.sirius.targets/sirius_2023-03.target, releng/org.eclipse.sirius.targets/sirius_2023-06.target, releng/org.eclipse.sirius.targets/sirius_2023-09.target, releng/org.eclipse.sirius.targets/sirius_2023-12.target, releng/org.eclipse.sirius.targets/sirius_2023-12.targetplatform
Change-Id: I5abb3dd8d9e5377e4bedb3840326549ad68bb418
=> [releng] Switch TPs to gmf-runtime 20231212

plugins/org.eclipse.sirius.doc/doc/i18n_changes.textile, plugins/org.eclipse.sirius/plugin.properties, plugins/org.eclipse.sirius/src/org/eclipse/sirius/business/internal/image/ImageManagerForWorkspaceResource.java, plugins/org.eclipse.sirius/src/org/eclipse/sirius/tools/api/Messages.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/127
=> [127] Get existing images folder name for ImageManager

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/layout/provider/BorderItemAwareLayoutProvider.java
A "cannot modify resource set without a write transaction" exception was thrown on the Layout Children action due to the pin/unpin of elementsToKeepFix when the command was created. We now use the elementsToKeepFix list directly.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/153
=> [153] Fix exception in Layout Children action

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/listeners/GMFBoundsUpdater.java
- WorkspaceImage style change can occur on DNode or DDiagramElementContainer: avoid potential ClassCastException.
- For DNode elements with the new auto-size feature, do not synchronize GMF layout constraints with the new DNode::height/width as it would cancel manual resize previously done by user. (Do not change behavior for other cases)
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/65
=> [65] Fix GMFBoundsUpdater

plugins/org.eclipse.sirius.diagram.elk/META-INF/MANIFEST.MF, plugins/org.eclipse.sirius.diagram.elk/plugin.properties, plugins/org.eclipse.sirius.diagram.elk/plugin.xml, plugins/org.eclipse.sirius.diagram.elk/src/org/eclipse/sirius/diagram/elk/DiagramElkPlugin.java, plugins/org.eclipse.sirius.diagram.elk/src/org/eclipse/sirius/diagram/elk/ELKLayoutNodeProvider.java, plugins/org.eclipse.sirius.diagram.elk/src/org/eclipse/sirius/diagram/elk/ElkDiagramLayoutConnector.java, plugins/org.eclipse.sirius.diagram.elk/src/org/eclipse/sirius/diagram/elk/Messages.java, plugins/org.eclipse.sirius.diagram.elk/src/org/eclipse/sirius/diagram/elk/migration/description/ELK090MigrationParticipant.java, plugins/org.eclipse.sirius.doc/doc/Release_Notes.html, plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile, plugins/org.eclipse.sirius.doc/doc/i18n_changes.html, plugins/org.eclipse.sirius.tests.junit/META-INF/MANIFEST.MF, plugins/org.eclipse.sirius.tests.junit/data/unit/migration/do_not_migrate/fromELK0.7.1To0.9.0/ELK0.7.1-0.9.0-changes.odesign, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/suite/common/AllCommonPluginTests.java, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/common/migration/ELK090VSMMigrationTest.java, releng/org.eclipse.sirius.targets/modules/elk-0.9.tpd, releng/org.eclipse.sirius.targets/sirius_2022-09.target, releng/org.eclipse.sirius.targets/sirius_2022-09.targetplatform, releng/org.eclipse.sirius.targets/sirius_2022-12.target, releng/org.eclipse.sirius.targets/sirius_2022-12.targetplatform, releng/org.eclipse.sirius.targets/sirius_2023-03.target, releng/org.eclipse.sirius.targets/sirius_2023-03.targetplatform, releng/org.eclipse.sirius.targets/sirius_2023-06.target, releng/org.eclipse.sirius.targets/sirius_2023-06.targetplatform, releng/org.eclipse.sirius.targets/sirius_2023-09.target, releng/org.eclipse.sirius.targets/sirius_2023-09.targetplatform, releng/org.eclipse.sirius.targets/sirius_2023-12.target, releng/org.eclipse.sirius.targets/sirius_2023-12.targetplatform
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/203
=> [203] Upgrade to ELK 0.9.0

plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/diagram/tools/palette/PaletteReloadAfterVSMChangeTest.java
=> [test] Fix test to compile on current GEF Classic

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/pinning/PinElementsAction.java
The pin/unpin button is now checked only if all selected pinnable elements are pinned.
=> [173] Change pin/unpin button activation policy with multiple selection

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/layout/PasteStylePureGraphicalAction.java, plugins/org.eclipse.sirius.ecore.extender/src/org/eclipse/sirius/ecore/extender/business/internal/permission/AbstractPermissionAuthority.java
=> [205] Fix bug in paste style action (missing removeAuthorityListener)

Jenkinsfile
=> [releng] Move to 1920x1200 screen resolution for UI tests

plugins/org.eclipse.sirius.tests.swtbot/data/unit/tools/creation/popupMenu/VP-1859/vp-1859.aird
=> [test] Fix GroupElementsInOneOtherTests when run at 1920x1200

plugins/org.eclipse.sirius.diagram.sequence/src/org/eclipse/sirius/diagram/sequence/business/internal/refresh/SequenceCanonicalSynchronizerAdapter.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/api/view/SiriusLayoutDataManager.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/internal/view/SiriusLayoutDataFlusher.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/internal/view/SiriusLayoutDataManagerImpl.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/graphical/figures/SiriusLayoutHelper.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/AbstractCanonicalSynchronizer.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/diagram/DDiagramCanonicalSynchronizer.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/layout/SiriusCanonicalLayoutCommand.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/layout/SiriusCanonicalLayoutHandler.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/format/MappingBasedSiriusFormatManagerFactory.java, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/diagram/layout/SimpleELKLayoutTest.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/CreatedElementsLayoutTests.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/DragNDropTest.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/ToolCreationPositionTest.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/layout/ContainerDefaultSizeLayoutTest.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/18
=> [18] Make diagram element layouts uniform during creation

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/pinning/PinElementsAction.java
Collectors.toMap doesn't accept null values.
=> [205] Fix potential NPE in PinElementsAction

packaging/org.eclipse.sirius.parent/pom.xml
Change sonar.coverage.jacoco.xmlReportPaths. The report seems to be generated in each project folder...
=> [releng] Update Sonar configuration

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/menu/DiagramEditorContextMenuProvider.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/153
=> [153] Fix NPE in contextual layout menu

plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/api/session/SampleSessionTest.java, plugins/org.eclipse.sirius/src/org/eclipse/sirius/business/internal/session/danalysis/DAnalysisSessionImpl.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/307
=> [307] Avoid NPEs if Session::close is called on a closed session

releng/org.eclipse.sirius.targets/sirius_canary.target
=> [releng] Fix URL for OCL nightly builds in canary

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/color/ColorManager.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/dialogs/ColorPaletteComposite.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/dialogs/ColorPalettePopup.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/dialogs/ColorSelectionDialog.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/323
=> [323] Improve the color palette drag&drop feedback

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/AbstractCanonicalSynchronizer.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/diagram/DDiagramCanonicalSynchronizer.java, plugins/org.eclipse.sirius.tests.swtbot/data/unit/dragAndDrop/bug318/My.ecore, plugins/org.eclipse.sirius.tests.swtbot/data/unit/dragAndDrop/bug318/My.odesign, plugins/org.eclipse.sirius.tests.swtbot/data/unit/dragAndDrop/bug318/representations.aird, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/DragDropWithUpdateNodeTest.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/318
=> [318] Disable refresh for removed children in CanonicalSynchronizer

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/dialogs/ColorPaletteComposite.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/dialogs/ColorSelectionDialog.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/BackgroundColorFigureUpdateTests.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/ChangeColorTest.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/HeaderSequenceDiagramTests.java
Tests have been updated after modifying drag & drop behavior and the basic color set.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/152
=> [152] Fix tests for color-changing menus

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/format/AbstractSiriusFormatDataManager.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/format/SiriusStyleApplicator.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/actions/layout/PasteStylePureGraphicalAction.java, plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/490444.aird, plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/490444.ecore, plugins/org.eclipse.sirius.tests.swtbot/data/unit/copyAppearance/My.odesign, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/tabbar/PasteStylePureGraphicalTest.java
https://github.com/eclipse-sirius/sirius-desktop/issues/346
=> [346] Support "Paste Style" when source and target are of different types

plugins/org.eclipse.sirius.doc/doc/user/diagrams/Diagrams.html, plugins/org.eclipse.sirius.doc/doc/user/diagrams/Diagrams.textile
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/346
=> [346] Update paste style documentation

plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/HeaderSequenceDiagramTests.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/152
=> [152] Fix sequence test by updating label color

plugins/org.eclipse.sirius.doc/doc/Release_Notes.html, plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile
=> [doc] Add release notes section for 7.4.2

plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/business/internal/metamodel/operations/DDiagramElementContainerWithInterpreterOperations.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/editor/vsm/ContainerDropPropertySectionsTests.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/layout/ELKDebugFeaturesTest.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/AllTestSuite.java
- [343] Fix tests that are KO under Linux OS 
- [380] Fix ContainerDropPropertySectionsTests regression
- [380] Fix bug in considering Drag'n'drop tools of other diagrams
=> PR to fix several regressions detected by automatic tests

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/business/internal/view/ShowingViewUtil.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/edit/internal/part/EditStatusUpdater.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/layout/provider/DefaultLayoutProvider.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/api/layout/provider/InlineEdgeLayoutProvider.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/palette/PaletteManagerImpl.java, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/diagram/layout/SimpleELKLayoutTest.java, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/diagram/tools/palette/AbstractPaletteManagerTest.java, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/diagram/tools/palette/PaletteManagerWithFiltersTest.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/PaletteManagerAfterVSMSelectionChange.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/341
=> [341] Adapt to GEF Classic 3.20/3.21 changes

plugins/org.eclipse.sirius.doc/doc/Release_Notes.html, plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile
=> [doc] Complete the release notes for v7.4.4

plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/business/internal/helper/task/CreateDEdgeTask.java, plugins/org.eclipse.sirius.diagram/src/org/eclipse/sirius/diagram/business/internal/sync/DDiagramSynchronizer.java, plugins/org.eclipse.sirius.tests.junit.support/src/org/eclipse/sirius/tests/support/api/SiriusDiagramTestCase.java, plugins/org.eclipse.sirius.tests.junit/data/unit/tool/bugEdge/My.ecore, plugins/org.eclipse.sirius.tests.junit/data/unit/tool/bugEdge/project.odesign, plugins/org.eclipse.sirius.tests.junit/data/unit/tool/bugEdge/representations.aird, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/suite/diagram/AllDiagramPluginsTests.java, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/api/tools/CreateEdgeTest.java, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/api/tools/CreateEdgeUnsyncBugTest.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/467
=> [467] Fix edge creation tool to create only the expected edge

plugins/org.eclipse.sirius.diagram.sequence.ui/src/org/eclipse/sirius/diagram/sequence/ui/tool/internal/edit/part/ObservationPointEditPart.java, plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/internal/refresh/CanonicalSynchronizerResult.java
=> [fix] Fix potential NPEs

plugins/org.eclipse.sirius.debug/src/org/eclipse/sirius/api/debug/AbstractDebugView.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/508
=> [508] Prevents NPE and index out of bound with Debug view.

plugins/org.eclipse.sirius.diagram.sequence/src/org/eclipse/sirius/diagram/sequence/internal/tool/command/builders/MessageCreationCommandBuilder.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/532
=> [532] Fix potential MetaClassNotFoundException in Sequence diagram

plugins/org.eclipse.sirius.tests.swtbot/data/unit/sequence/lifelines_tests/lifelines.aird, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/TwoSessionsTests.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/suite/SequenceSwtBotTestSuite.java
This test fails without the fix of the commit [1] bc0c58e4. In the console, the MetaClassNotFoundException can be observed (without the above fix).
The representations file has been updated to add a copy of the existing representation (with a different name).
[1] https://github.com/eclipse-sirius/sirius-desktop/commit/bc0c58e4e76a013034ca0ecc2c52e1fe7a1049df
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/532
=> [532] Add a corresponding automatic test

plugins/org.eclipse.sirius.common/src/org/eclipse/sirius/common/tools/api/query/IllegalStateExceptionQuery.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/548
=> [548] Match "Not Active: Transaction" in ConnectionLostException

plugins/org.eclipse.sirius.tests.junit/data/unit/session/modifySession/copy/representations.aird, plugins/org.eclipse.sirius.tests.junit/data/unit/session/modifySession/representations.aird
=> [cleanup] Fix broken references in test data

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/part/SiriusDiagramActionBarContributor.java
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/564
=> [564] Fix the action Auto Size in contextual menu

plugins/org.eclipse.sirius.table/src/org/eclipse/sirius/table/business/internal/refresh/DTableElementSynchronizer.java, plugins/org.eclipse.sirius.tests.junit/data/table/unit/refresh/tables.odesign, plugins/org.eclipse.sirius.tests.junit/data/table/unit/refresh/tables.uml, plugins/org.eclipse.sirius.tests.junit/src/org/eclipse/sirius/tests/unit/table/unit/refresh/DTableSynchronizerTest.java
One header label expression has been changed in data of test org.eclipse.sirius.tests.unit.table.unit.refresh.DTableSynchronizerTest.testVirtualFeatureColumns() to check the new behavior.
Bug: https://github.com/eclipse-sirius/sirius-desktop/discussions/556
Change-Id: I370741958d1b0757636e3a0b096dac1723a5585d
=> [556] Evaluate header label expression for Feature column

plugins/org.eclipse.sirius.doc/doc/Release_Notes.html, plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/558
=> [558] Mention the change in the release notes

plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/graphical/edit/policies/NodeCreationEditPolicy.java
In the previous commit [1], there were too many containers considered, without properly considering "extra mappings" (problems detected through StateBasicTests and PunctualStateTests).
[1] https://github.com/eclipse-sirius/sirius-desktop/commit/837813e95c6d09d448e2970ad7924eafb4cefa32
=> [396] Correctly consider extra mappings

plugins/org.eclipse.sirius/src/org/eclipse/sirius/business/internal/migration/description/VSMMigrationService.java
=> [fix] Fix a potential NPE in VSMMigrationService

releng/org.eclipse.sirius.targets/modules/eef-2.1.tpd, releng/org.eclipse.sirius.targets/sirius_2023-03.target, releng/org.eclipse.sirius.targets/sirius_2023-06.target, releng/org.eclipse.sirius.targets/sirius_2023-09.target, releng/org.eclipse.sirius.targets/sirius_2023-12.target, releng/org.eclipse.sirius.targets/sirius_2024-03.target, releng/org.eclipse.sirius.targets/sirius_2024-06.target, releng/org.eclipse.sirius.targets/sirius_2024-09.target, releng/org.eclipse.sirius.targets/sirius_2024-12.target, releng/org.eclipse.sirius.targets/sirius_2025-03.target
=> [releng] Switch to EEF 2.1.7

plugins/org.eclipse.sirius.doc/doc/Release_Notes.html, plugins/org.eclipse.sirius.doc/doc/Release_Notes.textile
See https://github.com/eclipse-sirius/sirius-website-sources/issues/25
=> [doc] Fix invalid XML syntax in the release notes

plugins/org.eclipse.sirius.tests.swtbot/data/unit/sequence/obliques/obliques.aird, plugins/org.eclipse.sirius.tests.swtbot/data/unit/sequence/obliques/obliques.interactions, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/AbstractObliqueMessagesSequenceTests.java, plugins/org.eclipse.sirius.tests.swtbot/src/org/eclipse/sirius/tests/swtbot/sequence/ObliqueMessagesTests.java
Tests for oblique messages between Gates of different containers were
missing.
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/620
=> [620] Add test cases for oblique message between 2 Gates

plugins/org.eclipse.sirius.doc/build-doc.xml, plugins/org.eclipse.sirius.doc/doc/Release_Notes_Previous.html, plugins/org.eclipse.sirius.doc/doc/Release_Notes_Previous.textile, plugins/org.eclipse.sirius.doc/doc/developer/trigger-refresh-graphical-changes.html, plugins/org.eclipse.sirius.doc/doc/developer/trigger-refresh-graphical-changes.textile, plugins/org.eclipse.sirius.doc/doc/specifier/diagrams/Diagrams.html, plugins/org.eclipse.sirius.doc/doc/specifier/tables/Tables.html, plugins/org.eclipse.sirius.doc/doc/specifier/trees/Trees.html
=> [doc] Fix some broken links in the documentation

releng/org.eclipse.sirius.targets/sirius_canary.target
=> [releng] Fix canary target platform
